# Use the official Node.js image for React development
FROM node:16-alpine

# Set the working directory inside the container
WORKDIR /app

# Add node_modules/.bin to PATH
ENV PATH /app/node_modules/.bin:$PATH

# Prevent interactive prompts during build
ENV BROWSERSLIST_DISABLE_CACHE=1
ENV CI=true

# Copy package.json and package-lock.json to leverage Docker caching
COPY package.json .
COPY package-lock.json .

# Install Node.js dependencies
RUN npm install

# Copy the entire frontend folder, including source code and public files
COPY . .

# Expose the port that the React app will run on
EXPOSE 3000

# Command to start the React application
CMD ["npm", "start"]
