version: "3.8"

services:
  backend:
    build:
      context: ./backend  # Context points to the 'backend' folder
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app  # Mount 'app' folder to '/app/app'
    environment:
      - PYTHONUNBUFFERED=1
